Add tests
jfrog/jenkins-jfrog-plugin pull request #17
Opened 2022-12-22 16:07 UTC by gailazar300

- [x] This pull request is created in the [jfrog/jenkins-jfrog-plugin](https://github.com/jfrog/jenkins-jfrog-plugin) repository.

2022-12-24 12:22 UTC, yahavi requested changes
Well done, @gailazar300!
Please consider my inline comments.

Also, a few general comments - 
1. The integration tests are running as **unit** tests. To fix this, do the following:
A. Rename JFrogInstallationTest -> JFrogInstallationITest
B. Configure maven-surefire-plugin and maven-failsafe-plugin as we do here - https://github.com/jfrog/jenkins-artifactory-plugin/blob/artifactory-3.17.4/pom.xml#L596
3. The tests are running every time I ran `mvn package`. To prevent this, please use the `skipITs` property. See this example - https://github.com/jfrog/jenkins-artifactory-plugin/blob/artifactory-3.17.4/pom.xml#LL42C13-L42C13
4. Please reformat all files in this PR.
5. Let's explain in README.md or in CONTRIBUTING.md (better) how to run the tests.
4. As much as possible, prepare the test environment before all tests and tear it down after all tests
5. Delete repositories after the tests.

2022-12-24 12:22 UTC, yahavi commented on pom.xml
> +            <version>2.11.1</version>
Let's use the latest
```suggestion
            <version>2.13.0</version>
```

2022-12-24 12:22 UTC, yahavi commented on pom.xml
> +            <version>2.11.1</version>
```suggestion
            <version>2.13.0</version>
```

2022-12-24 12:22 UTC, yahavi commented on pom.xml
> +            <version>4.5.3</version>
```suggestion
            <version>4.7.3</version>
```

2022-12-24 12:22 UTC, yahavi commented on pom.xml
> +                <version>4.5.3.0</version>
```suggestion
                <version>4.7.3.0</version>
```

2022-12-24 12:22 UTC, yahavi commented on pom.xml
> +                            <version>1.10.1</version>
```suggestion
                            <version>1.12.0</version>
```

2022-12-24 12:22 UTC, yahavi commented on src/test/java/io/jenkins/plugins/jfrog/integration/JFrogInstallationTest.java
> +    public static final String jfrogCliTestVersion = "2.29.2";
Can be private

2022-12-24 12:22 UTC, yahavi commented on src/test/java/io/jenkins/plugins/jfrog/integration/JFrogInstallationTest.java
> +    // JFrog CLI version which is accessible for all operating systems.
This is true only for now :)
```suggestion
```

2022-12-24 12:22 UTC, yahavi commented on src/test/java/io/jenkins/plugins/jfrog/integration/JFrogInstallationTest.java
> +     * Download Jfrog CLI from 'releases.io' and adds it as a global tool.
```suggestion
     * Downloads JFrog CLI from 'releases.jfrog.io' and adds it as a global tool.
```

2022-12-24 12:22 UTC, yahavi commented on src/test/java/io/jenkins/plugins/jfrog/integration/JFrogInstallationTest.java
> +package io.jenkins.plugins.jfrog.integration;
Please reformat the code in this and in all other files

2022-12-24 12:22 UTC, yahavi commented on src/test/java/io/jenkins/plugins/jfrog/integration/JFrogInstallationTest.java
> +        setupPipelineTest(jenkins);
Instead of repeating this line in all test, you can create a new function with `@BeforeEach` annotation:
```java
@BeforeEach
public void setupTest() {
    ...
}
```
Use `@AfterEach` for the cleanups, if needed

https://junit.org/junit5/docs/current/user-guide/#writing-tests-annotations

2022-12-24 12:22 UTC, yahavi commented on src/test/java/io/jenkins/plugins/jfrog/integration/PipelineTestBase.java
> +    public static void setUp() throws IOException {
It would be much better to run this setup exactly once, before all tests.
```suggestion
    @BeforeAll
    public static void setUp() throws IOException {
```

2022-12-24 12:22 UTC, yahavi commented on src/test/java/io/jenkins/plugins/jfrog/integration/PipelineTestBase.java
> +    public static JfrogInstallation configureJfrogCliFromReleases(String toolName, String cliVersion, Boolean override) throws IOException {
Looks like the toolName is always the same

2022-12-24 12:22 UTC, yahavi commented on src/test/java/io/jenkins/plugins/jfrog/integration/JFrogInstallationTest.java
> +    public void testJfrogCliInstallationFromReleases(JenkinsRule jenkins) throws Exception{
```suggestion
    public void testJFrogCliInstallationFromReleases(JenkinsRule jenkins) throws Exception{
```

2022-12-24 12:22 UTC, yahavi commented on src/test/java/io/jenkins/plugins/jfrog/integration/JFrogInstallationTest.java
> +     * Download Jfrog CLI from client Artifactory and adds it as a global tool.
```suggestion
     * Download JFrog CLI from client Artifactory and adds it as a global tool.
```

2022-12-24 12:22 UTC, yahavi commented on src/test/java/io/jenkins/plugins/jfrog/integration/JFrogInstallationTest.java
> +    public void testJfrogCliInstallationFromArtifactory(JenkinsRule jenkins) throws Exception{
```suggestion
    public void testJFrogCliInstallationFromArtifactory(JenkinsRule jenkins) throws Exception{
```

2022-12-24 12:22 UTC, yahavi commented on src/test/java/io/jenkins/plugins/jfrog/integration/JFrogInstallationTest.java
> +     * @param jenkins Jenkins instance Injected automatically.
(Same in other places in this file)
```suggestion
     * @param jenkins Jenkins instance injected automatically.
```

2022-12-24 12:22 UTC, yahavi commented on src/test/java/io/jenkins/plugins/jfrog/integration/JFrogInstallationTest.java
> +        // Using remote repository to 'releases.io' in the client's Artifactory.
```suggestion
        // Using remote repository to 'releases.jfrog.io' in the client's Artifactory.
```

2022-12-24 12:22 UTC, yahavi commented on src/test/java/io/jenkins/plugins/jfrog/integration/JFrogInstallationTest.java
> +        Path binaryPath = toolDirPath;
Redundant variable
```suggestion
        Path binaryPath = getJfrogInstallationDir(jenkins);
```

2022-12-24 12:22 UTC, yahavi commented on src/test/java/io/jenkins/plugins/jfrog/integration/JFrogInstallationTest.java
> +            name = name + ".exe";
```suggestion
            name += ".exe";
```

2022-12-24 12:22 UTC, yahavi commented on src/test/java/io/jenkins/plugins/jfrog/integration/JFrogInstallationTest.java
> +        assertTrue(binaryPath.toFile().exists());
```suggestion
        assertTrue(Files.exists(binaryPath));
```

2022-12-24 12:22 UTC, yahavi commented on src/test/java/io/jenkins/plugins/jfrog/integration/JFrogInstallationTest.java
> +    //
```suggestion
```

2022-12-24 12:22 UTC, yahavi commented on src/test/java/io/jenkins/plugins/jfrog/integration/JFrogInstallationTest.java
> +     * Check that only one copy of maven extractor is being downloaded to the expected 'dependencies' directory by running a script with a maven command.
```suggestion
     * Check that only one copy of the Maven extractor is downloaded to the expected 'dependencies' directory.
```

2022-12-24 12:22 UTC, yahavi commented on src/test/java/io/jenkins/plugins/jfrog/integration/JFrogInstallationTest.java
> +        File[] fileList = mvnDependenciesDirPath.toFile().listFiles();
```suggestion
        File[] fileList = mvnDependenciesDirPath.toFile().listFiles();
        assertNotNull(fileList);
```

2022-12-24 12:22 UTC, yahavi commented on src/test/java/io/jenkins/plugins/jfrog/integration/JFrogInstallationTest.java
> +        fileList = extractorPath.toFile().listFiles();
```suggestion
        fileList = extractorPath.toFile().listFiles();
        assertNotNull(fileList);
```

2022-12-24 12:22 UTC, yahavi commented on src/test/java/io/jenkins/plugins/jfrog/integration/JFrogInstallationTest.java
> +        return 0;
Please consider this:
```suggestion
        try (Stream<Path> mavenExtractorFiles = Files.list(extractorPath)) {
            Path jar = mavenExtractorFiles.filter(file -> file.toString().endsWith(".jar")).findFirst().orElse(null);
            assertNotNull(jar, "Couldn't file the build-info-extractor-maven3 jar in " + extractorPath);
            return Files.getLastModifiedTime(jar).toMillis();
        }
```

2022-12-24 12:22 UTC, yahavi commented on src/test/java/io/jenkins/plugins/jfrog/integration/JFrogInstallationTest.java
> +        // Download the latest CLI version from releases.io and from Artifactory.
```suggestion
        // Download the latest CLI version from releases.jfrog.io and from Artifactory.
```

2022-12-24 12:22 UTC, yahavi commented on src/test/java/io/jenkins/plugins/jfrog/integration/JFrogInstallationTest.java
> +        // Download the latest CLI version from Artifactory and then a specific version from releases.io.
```suggestion
        // Download the latest CLI version from Artifactory and then a specific version from releases.jfrog.io.
```

2022-12-24 12:22 UTC, yahavi commented on src/test/java/io/jenkins/plugins/jfrog/integration/JFrogInstallationTest.java
> +        runPipeline(jenkins, "basic_commands_2");
Let's verify the version/s

2022-12-24 12:22 UTC, yahavi commented on src/test/java/io/jenkins/plugins/jfrog/integration/PipelineTestBase.java
> +    public static final String TEST_CONFIGURED_SERVER_ID = "serverId";
Many of these variables can be private, and I think that the others can be package-private

2022-12-24 12:22 UTC, yahavi commented on src/test/java/io/jenkins/plugins/jfrog/integration/PipelineTestBase.java
> +        this.jenkins = jenkins;
Let's never ignore compiler warnings
```suggestion
        PipelineTestBase.jenkins = jenkins;
```

2022-12-24 12:22 UTC, yahavi commented on src/test/java/io/jenkins/plugins/jfrog/integration/PipelineTestBase.java
> +     * Creates build-info and Artifactory Java clients.
```suggestion
     * Creates Artifactory Java client.
```

2022-12-24 12:22 UTC, yahavi commented on src/test/java/io/jenkins/plugins/jfrog/integration/PipelineTestBase.java
> +        System.out.println(job.getLog());
```suggestion
```

2022-12-24 12:22 UTC, yahavi commented on src/test/java/io/jenkins/plugins/jfrog/integration/PipelineTestBase.java
> +    private static void addCreds(CredentialsStore store, CredentialsScope scope, String id) throws IOException {
Please consider the compiler warnings
```suggestion
    private static void addCreds(CredentialsStore store) throws IOException {
```

2022-12-24 12:22 UTC, yahavi commented on src/test/java/io/jenkins/plugins/jfrog/integration/PipelineTestBase.java
> +        return store;
```suggestion
        return stores.next();
```

2022-12-24 12:22 UTC, yahavi commented on src/test/java/io/jenkins/plugins/jfrog/integration/PipelineTestBase.java
> +            put("JFROG_CLI_TOOL_NAME2", JFROG_CLI_TOOL_NAME2);
Let's change in all places, accordingly
```suggestion
            put("JFROG_CLI_TOOL_NAME_1", JFROG_CLI_TOOL_NAME_1);
            put("JFROG_CLI_TOOL_NAME_2", JFROG_CLI_TOOL_NAME_2);
```

2022-12-24 12:22 UTC, yahavi commented on src/test/java/io/jenkins/plugins/jfrog/integration/PipelineTestBase.java
> +            put("REMOTE_REPO1", getRepoKey(TestRepository.CLI_REMOTE_REPO));
Since there is no "2", we don't need "1"
```suggestion
            put("LOCAL_REPO", getRepoKey(TestRepository.LOCAL_REPO));
            put("REMOTE_REPO", getRepoKey(TestRepository.CLI_REMOTE_REPO));
```

2022-12-24 12:22 UTC, yahavi commented on src/test/java/io/jenkins/plugins/jfrog/integration/PipelineTestBase.java
> +    }
The return value of these functions is never used

2022-12-24 12:22 UTC, yahavi commented on src/test/java/io/jenkins/plugins/jfrog/integration/PipelineTestBase.java
> +        DescribableList<ToolProperty<?>, ToolPropertyDescriptor> r = new DescribableList<>(NOOP);
What is "r"? Let's use meaningful names, like "toolProperties"

2022-12-24 12:22 UTC, yahavi commented on src/test/java/io/jenkins/plugins/jfrog/integration/PipelineTestBase.java
> +        ArrayList<JfrogInstallation> arrayList = new ArrayList<>();
Let's use meaningful names

2022-12-24 12:22 UTC, yahavi commented on src/test/java/io/jenkins/plugins/jfrog/integration/PipelineTestBase.java
> +        JfrogInstallation[] installations = Arrays.asList(arrayList.toArray()).toArray(new JfrogInstallation[arrayList.size()]);
```suggestion
        JfrogInstallation[] installations = arrayList.toArray(new JfrogInstallation[0]);
```

2022-12-24 12:22 UTC, yahavi commented on src/test/java/io/jenkins/plugins/jfrog/integration/TestRepository.java
> +    ;
```suggestion
    CLI_REMOTE_REPO("jenkins-jfrog-tests-cli-remote", RepoType.REMOTE);
```

2022-12-24 12:22 UTC, yahavi commented on src/test/java/io/jenkins/plugins/jfrog/integration/TestRepository.java
> +        VIRTUAL
Not in use
```suggestion
```

2022-12-24 12:22 UTC, yahavi commented on src/test/java/io/jenkins/plugins/jfrog/integration/TestRepository.java
> +    private RepoType repoType;
Fix compiler errors
```suggestion
    private final String repoName;
    private final RepoType repoType;
```

2022-12-24 12:22 UTC, yahavi commented on src/test/java/io/jenkins/plugins/jfrog/integration/TestRepository.java
> +    }
Not in use
```suggestion
```

2022-12-24 12:22 UTC, yahavi commented on src/test/resources/integration/pipelines/basic_commands.pipeline
> +                jf 'c show'
For security reasons, let's try to avoid showing the running server configurations
```suggestion
```

2022-12-24 12:22 UTC, yahavi commented on src/test/resources/integration/pipelines/basic_commands.pipeline
> +                jf 'rt bp'
It is hard to clean up builds and I don't see any extra value in publish them
```suggestion
```

2022-12-24 12:22 UTC, yahavi commented on src/test/resources/integration/pipelines/basic_commands_2.pipeline
> +                jf 'rt bp'
```suggestion
```

2022-12-24 12:22 UTC, yahavi commented on src/test/resources/integration/settings/jenkins-jfrog-tests-cli-remote.json
> +  "packageType": "go",
Go?
```suggestion
  "packageType": "generic",
```

2022-12-24 12:22 UTC, yahavi commented on src/test/resources/integration/settings/jenkins-jfrog-tests-local-1.json
> +  "rclass": "local"
```suggestion
  "packageType": "generic",
  "rclass": "local"
```

2022-12-24 12:22 UTC, yahavi commented on src/test/resources/integration/settings/jenkins-jfrog-tests-local-1.json
> +{
Let's remove the "1" from the file name (because there is no "2")

2022-12-27 09:51 UTC, gailazar300 commented on src/test/java/io/jenkins/plugins/jfrog/integration/JFrogInstallationTest.java
> +    // JFrog CLI version which is accessible for all operating systems.
why?

2022-12-27 10:33 UTC, yahavi commented on src/test/java/io/jenkins/plugins/jfrog/integration/JFrogInstallationTest.java
> +    // JFrog CLI version which is accessible for all operating systems.
Because tomorrow there may be a release of a new architecture for Mac or Linux or Windows or a completely new OS

2022-12-29 13:26 UTC, merged