Default setting of JFrog CLI relevant environment variables
jfrog/jenkins-jfrog-plugin pull request #8
Opened 2022-11-13 17:19 UTC by gailazar300

- [x] This pull request is created in the [jfrog/jenkins-jfrog-plugin](https://github.com/jfrog/jenkins-jfrog-plugin) repository.

Set 4 environment variables with a default value (in case they are empty):
1. JFROG_CLI_DEPENDENCIES_DIR: 
    By doing this, we avoid downloading dependencies separately for each job in its temporary Jfrog home directory.
2. JFROG_CLI_BUILD_NAME & JFROG_CLI_BUILD_NUMBER
3. JFROG_CLI_BUILD_URL

2022-11-19 10:19 UTC, eyalbe4 requested changes

2022-11-19 10:19 UTC, eyalbe4 commented on src/main/java/io/jenkins/plugins/jfrog/JfStep.java
> +     * @param run             running as a part of a specific build
...as a part... --> ...as part...

2022-11-20 08:21 UTC, yahavi requested changes

2022-11-20 08:21 UTC, yahavi commented on src/main/java/io/jenkins/plugins/jfrog/JfStep.java
> +        }
We can remove code duplication by doing the following:
```suggestion
        // Setting Jenkins job name as the default build-info name.
        env.putIfAbsent(JFROG_CLI_BUILD_NAME, env.get("JOB_NAME"));
        // Setting Jenkins build number as the default build-info number.
        env.putIfAbsent(JFROG_CLI_BUILD_NUMBER, env.get("BUILD_NUMBER"));
        // Setting the specific build URL.
        env.putIfAbsent(JFROG_CLI_BUILD_URL, env.get("BUILD_URL"));
```

2022-11-20 08:21 UTC, yahavi commented on src/main/java/io/jenkins/plugins/jfrog/JfStep.java
> +        env.put(JFROG_CLI_HOME_DIR, jfrogHomeTempDir.getRemote());
Shouldn't we check for the absence of `JFROG_CLI_HOME_DIR` before setting it?

2022-11-20 08:21 UTC, yahavi commented on src/main/java/io/jenkins/plugins/jfrog/JfrogInstallation.java
> +            env.put(JFROG_CLI_USER_AGENT, "jenkins-jfrog-plugin");
The user agent should contain the version too (add null checks):
```java
Jenkins.getInstanceOrNull().getPlugin("jfrog").getWrapper().getVersion()
```

2022-11-20 08:21 UTC, yahavi commented on src/main/java/io/jenkins/plugins/jfrog/JfrogInstallation.java
> +        }
```suggestion
        env.putIfAbsent(JFROG_CLI_USER_AGENT, "jenkins-jfrog-plugin");
```

2022-11-20 12:52 UTC, merged